### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by seaneble** [heimrichhannot/contao-formhybrid#1]
There is a discrepancy between composer and the autoloader configuration:

https://github.com/heimrichhannot/contao-formhybrid/blob/master/config/autoload.ini#L5
https://github.com/heimrichhannot/contao-formhybrid/blob/master/composer.json#L19

As a result, one cannot install formhybrid via Composer:

```
The module dependencies could not be resolved.
Array
(
    [formhybrid] => Array
        (
            [0] => core
            [1] => bootstrapper
        )

)
```

Please update the composer.json accordingly.

**Comment by fatcrobat** [comment]
Thanks for that, we removed the bootstrapper dependency from bootstrapper within the latest tag.

**Comment by seaneble** [comment]
Perfect, thanks!
