### ISSUE TITLE
Fehler unknown column memberusername beim Hinzufügen eines neuen Formularfeldes

### ISSUE THREAD

**Issue by basistom** [heimrichhannot/contao-formhybrid#2]
Nach der Installation von Formhybrid (als Vorraussetzung für die Multifileupload-Erweitertung) bekomme ich beim Hinzufügen bzw. Bearbeiten eines Formularfeldes folgenden Fehler:

`Fatal error: Uncaught exception Exception with message Query error: Unknown column 'memberusername' in 'field list' (SELECT tstamp, version, username, memberusername, active FROM tl_version WHERE fromTable='tl_form_field' AND pid='601' ORDER BY version DESC) thrown in system/modules/core/library/Contao/Database/Statement.php on line 295
#0 system/modules/core/library/Contao/Database/Statement.php(264): Contao\Database\Statement->query()
#1 system/modules/formhybrid/classes/Versions.php(526): Contao\Database\Statement->execute('tl_form_field', '601')
#2 system/modules/core/drivers/DC_Table.php(1962): Contao\Versions->renderDropdown()
#3 system/modules/core/classes/Backend.php(650): Contao\DC_Table->edit()
#4 system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('form')
#5 contao/main.php(20): Contao\BackendMain->run()
#6 {main}`

**Comment by fatcrobat** [comment]
Thanks for the report, forgot to add contao-versions as composer dependency. Please update composer to version 2.5.25
