### ISSUE TITLE
PHP 7

### ISSUE THREAD

**Issue by internethering** [heimrichhannot/contao-formhybrid#3]
Hi, 

older releases support PHP 7, newer not. Please fix this for all packages ;) Contao is php 7 compatible since 3.5.5

```
Installation request for heimrichhannot/contao-formhybrid >=2.6.10.0,<2.7-dev -> satisfiable by heimrichhannot/contao-formhybrid[2.6.10].
    - heimrichhannot/contao-formhybrid 2.6.10 requires php >=5.4.0, <7 -> your PHP version (7.1.1) does not satisfy that requirement.
```

**Comment by fatcrobat** [comment]
We did lock our modules via composer to not support php7 as we did not test them against php7 yet. But we currently move to php7 and our modules will support php7 shortly.

**Comment by koertho** [comment]
I think, I can close this, as we have this module active in a lot of PHP7.x projects.
