### ISSUE TITLE
3.9.3 requires abandoned packages

### ISSUE THREAD

**Issue by DrAColian** [heimrichhannot/contao-formhybrid#5]
The following packages are marked as abandoned and shouldn't be used, but are still required by formhybrid:
`	"heimrichhannot/contao-ajax": "^1.1.1",
	"heimrichhannot/contao-be_explanation": "~1.0",
	"heimrichhannot/contao-inserttag_download": "~1.0"`

Could you please change those to the "bundled" versions!?
Thanks.

**Comment by koertho** [comment]
@DrAColian We were a litte to hasty abandon this packages. We can't upgrade those all to the bundled version, as formhybrid needs to be compatible with contao 3.

Our long-term-goal is to overhaul formhybrid completly, but this will still take some time.

**Comment by DrAColian** [comment]
@koertho any chance of getting a "dependent" requirement? so, if Contao 4.X is installed, then the bundled versions are used, otherwise the "abandoned" ones?

**Comment by koertho** [comment]
@DrAColian No, it is not as easy as it sounds, as the bundle often also change the api.
As said, sometimes in the future this will change, but not now.
