### ISSUE TITLE
Error - Contao 4.10.2

### ISSUE THREAD

**Issue by jankout** [heimrichhannot/contao-formhybrid#6]
If I try to install https://github.com/heimrichhannot/contao-calendar_plus following error occurs.
 
`Could not load package heimrichhannot/contao-formhybrid in http://repo.packagist.org: [UnexpectedValueException] Could not parse version constraint >=1.0.14,,<2.0.0-dev: Invalid version string "1.0.14,,<2.0.0-dev"`

**Comment by koertho** [comment]
@jankout Which version of calendar_plus? Current version has `"heimrichhannot/contao-formhybrid": "^3.0"`.

**Comment by jankout** [comment]
the calendar_plus extension I found in over Contao Manager takes the older version of your extension. But this happens since 4.10.x. Before when I used the Contao 4.9.x version I could install and update it. I guess there is something new for 4.10.x? 

I've also tried to install the master dev version but it didn't work too.

**Comment by koertho** [comment]
In my opinion this is a problem of the calendar_plus module. Formhybrid works at least for contao 4.9. Calendar plus is not actively maintained anymore, but if you found the problem, you can post it there.
